{
 "title": "StockSnake",
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Flatex-Depot",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Value-total\" AS \"Depotwert\", \"Invested-total\" as \"Investiert\" FROM \"Depots\" WHERE (\"Depot\" = 'Flatex') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flatex - Abweichung zum Ziel",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"delta-DE000ETFL078\", \"delta-DE000ETFL284\", \"delta-DE000ETFL375\", \"delta-IE00B14X4M10\", \"delta-IE00B3F81G20\", \"delta-IE00B4L5YC18\", \"delta-LU0392495023\", \"delta-LU0392496005\", \"delta-LU0419741177\", \"delta-total\" FROM \"Depots\" WHERE (\"Depot\" = 'Flatex') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Einzelwerte-Depot",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Value-total\" AS \"Depotwert\", \"Invested-total\" as \"Investiert\" FROM \"Depots\" WHERE (\"Depot\" = 'Einzelwerte') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heidelberger Druck",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "measurement": "StockValues",
     "query": "SELECT \"delta-DE000ETFL078\", \"delta-DE000ETFL284\", \"delta-DE000ETFL375\", \"delta-IE00B14X4M10\", \"delta-IE00B3F81G20\", \"delta-IE00B4L5YC18\", \"delta-LU0392495023\", \"delta-LU0392496005\", \"delta-LU0419741177\", \"delta-total\" FROM \"Depots\" WHERE (\"Depot\" = 'Flatex') AND $timeFilter",
     "select": [
      [
       { "params": [ "close" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "Heidelberger Druck" }
     ]
    }
   ]
  },
  {
   "title": "Script Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Name AS \"Script\",\n  Status as \"Status\",\n  StatusMessage as \"Message\",\n  StatusDateTime as \"Updated\",\n  StartDateTime AS \"Started\",\n  EndDateTime AS \"Completed\",\n  ErrorMessage AS \"ErrMsg\",\n  TIMESTAMPDIFF(HOUR, LastSuccessDateTime,NOW()) as \"Pause\"\nFROM scriptstatus\nORDER BY Name"
    }
   ]
  },
  {
   "title": "Log",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  Id AS \"Id\",\n  DATE_FORMAT(LogTime, '%d.%m%.%y %H:%i:%s') AS \"LogTime\",\n  LogLevelName as \"LogLevel\",\n  LogUser as \"Source\",\n  LogMsg as \"Message\"\nFROM log\nORDER BY Id desc\nlimit 100"
    }
   ]
  }
 ]
}