{
 "title": "StockSnake-Board",
 "description": "Production version of the StockSnake-Board",
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Depots",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"stocks\",\r\n  tag: \"Depot\",\r\n  predicate: (r) => true,\r\n  start: -30y\r\n)"
   }
  ]
 },
 "panels": [
  { "title": "Übersicht $Depots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Depots" },
  {
   "title": "$Depots - XIRR 180 days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"stocks\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"KPIs\")\r\n  |> filter(fn: (r) => r[\"Depot\"] == \"$Depots\")\r\n  |> filter(fn: (r) => r[\"KPI\"] == \"XIRR-180\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"KPI-Value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Value $Depots-Depot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"stocks\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Depots\")\r\n  |> filter(fn: (r) => r[\"Depot\"] == \"$Depots\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Invested-total\" or r[\"_field\"] == \"Value-total\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deviations $Depots-Depot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"stocks\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Depots\")\r\n  |> filter(fn: (r) => r[\"Depot\"] == \"$Depots\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /delta-.*/ )\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Depots - XIRR 1 Year",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"stocks\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"KPIs\")\r\n  |> filter(fn: (r) => r[\"Depot\"] == \"$Depots\")\r\n  |> filter(fn: (r) => r[\"KPI\"] == \"XIRR-365\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"KPI-Value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Depots - XIRR 3 Years",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"stocks\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"KPIs\")\r\n  |> filter(fn: (r) => r[\"Depot\"] == \"$Depots\")\r\n  |> filter(fn: (r) => r[\"KPI\"] == \"XIRR-1095\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"KPI-Value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Einzelwerte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Value E.ON",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"stocks\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"StockValues\")\r\n  |> filter(fn: (r) => r[\"ISIN\"] == \"DE000ENAG999\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"close\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Value UNIPER",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"stocks\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"StockValues\")\r\n  |> filter(fn: (r) => r[\"ISIN\"] == \"DE000UNSE018\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"close\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Value Volkswagen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"stocks\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"StockValues\")\r\n  |> filter(fn: (r) => r[\"ISIN\"] == \"DE0007664039\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"close\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Value Arero",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"stocks\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"StockValues\")\r\n  |> filter(fn: (r) => r[\"Name\"] == \"ARERO-Der Weltfonds - EUR ACC\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"close\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Job-Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT\n  Name,\n  StatusDateTime,\n  EndDateTime,\n  Status,\n  StatusMessage,\n  ErrorNumbers,\n  ErrorMessage,\n  WarningNumbers,\n  WarningMessage\nFROM ScriptStatus\n\nORDER BY EndDateTime"
    }
   ]
  }
 ]
}